### PR TITLE
CMake files fixes

### PR DESCRIPTION
**Pull request by aleksey-nikolaev**
* The executables and libs are created like in the Makefile.am
* Correct version for project
* Options for build mostly like in the configure.ac
* Used find_package instead directly finding of files 
* MSVC specific (winGetOpt, warnings, definitions)

### CODE REVIEW

**Comment by fukuchi** [comment]
Dear @aleksey-nikolaev 

Thank you for your contribution. Because I am not familiar with CMake system, I need your help to understand the request you've pushed.

* Why did you changed the cases of the command in 3aee5b3?
* Can you figure out the reason why the last test on Travis failed?
* Let me know which version of VisualStudio you used.

**Comment by aleksey-nikolaev** [comment]
Hi, @fukuchi 

* Uppercase for cmake command is old style. I use case as https://cmake.org/cmake/help/v3.0/ used.
* I made changes only for cmake part of your project. 
 This is can not affect the autolool build system. I don`t know what happened with $TRAVIS_BUILD_DIR/build/tests.
* I use VS2015

**Comment by aleksey-nikolaev** [comment]
Oh, I am sorry
 ./cmake-3.1.0-Linux-x86_64/bin/cmake .. -DBUILD_SHARED_LIBS=on -DBUILD_TESTING=on && make
I use options for build like used in your configure.ac, so use please
`-DWITH_TESTS=on` instead `-DBUILD_TESTING=on`
Also, `BUILD_SHARED_LIBS` option was used incorrectly, IMHO. Usually it used when need to make shared libs (dll, instead static lib), but in your case it used for making libqrencode.pc and some installs.

**Comment by aleksey-nikolaev** [comment]
last commit fix this
-- Could NOT find ICONV (missing:  ICONV_COMPILES)

**Comment by aleksey-nikolaev** [comment]
```bash
./cmake-3.1.0-Linux-x86_64/bin/cmake .. -DBUILD_SHARED_LIBS=on -DBUILD_TESTING=on && make
DESTDIR=$PWD/install make install
```
Probably better way to set (change) installation path is to set cmake option  CMAKE_INSTALL_PREFIX. Something like that:
```bash
./cmake-3.1.0-Linux-x86_64/bin/cmake ..  -DWITH_TESTS=ON -DCMAKE_INSTALL_PREFIX=$PWD/install && make && make install
```

**Comment by aleksey-nikolaev** [comment]
@fukuchi , I can`t understand what happened with iconv compiling test. I just remove it, maybe someone who better understand cmake and/or iconv could help.

So, could you change cmake build options, please?

./cmake-3.1.0-Linux-x86_64/bin/cmake ..  -DWITH_TESTS=ON -DCMAKE_INSTALL_PREFIX=$PWD/install && make && make install

**Comment by vilppuvuorinen** [comment]
This is significant improvement on the current CMake build. Would go for squash & merge.

I'm using CMake with GUI and I have to clear `GETOPT_INCLUDE_DIR` and `GETOPT_LIBRARIES` manually to get rid of errors when building without tools. This is a minor inconvenience but solution in CMakeLists.txt would be optimal.

Due to LGPL licensing `BUILD_SHARED_LIBS` is a must. It's quite elegant to just add the parameter and conditionally set the SHARED parameter to `add_library`. Additionally setting `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` on MSVC is a plus. See for reference: https://github.com/jubicoy/libqrencode/commit/ce9092a2c3ca933aada86de96e850c637ec7c45a

**Comment by fukuchi** [comment]
Thank you for your great contribution, @aleksey-nikolaev . Soon I'll merge it.
Thank you @vilppuvuorinen too for pushing me forward. ;)

**Pull request closed without merging**
