### PR TITLE
Add LDFLAGS for mingw compilation

### PR DESCRIPTION
**Pull request by EckoEdc**

### CODE REVIEW

**Comment by PipoloyJo** [comment]
Bump on this one? This would be really usefull to our project

**Comment by EckoEdc** [comment]
Hi,
this is a really simple change. Do you think you'll merge it ? Or is something wrong with it ? 

Thanks,

**Comment by fukuchi** [comment]
Hi @EckoEdc , thank you for the patch. Now I successfully confirmed this PR.

Some studies suggest that we can migrate the options you suggested to Makefile.am. Soon after I'll do that.

**Comment by fukuchi** [comment]
Done with 38bf8874.

**Pull request merged**
