### PR TITLE
Fix build on windows with Visual Studio

### PR DESCRIPTION
**Pull request by Ation**
Visual Studio does not support GCC attributes.

### CODE REVIEW

**Comment by fukuchi** [comment]
Hi @Ation ,

Thank you for the PR. Soon I'll apply it.

Just a question: how do you compile libqrencode with Visual Studio? A couple of times a year I receive this question.

**Comment by fukuchi** [comment]
Cherry-picked in 4.0 branch.

**Comment by Ation** [comment]
I simply generate project with cmake like this:
cmake -DWITH_TOOLS=NO -G Visual Studio 15 Win64 .

**Comment by fukuchi** [comment]
Thanks!

**Pull request merged**
